[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dexter = "7FqhXgUYkqLWCwMGv3R9tNd149oXwy9FqzS8d8HpU3W2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
